### ISSUE TITLE
Model hangs when doing 1 month runs

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#105]
@aekiss has been experiencing hangs when running the 0.1 for 1 month intervals. This looks like it could be a bug with YATM timekeeping.

**Comment by aekiss** [comment]
Awesome, thanks @nicjhan!
I had 8 1-month runs with YATM - will these have been affected by this bug?

**Comment by nicjhan** [comment]
Hi @aekiss, this is now fixed and pushed (there are new exes etc). The bug won't have any impact on past runs, it was just causing a hang for specific dates and runtimes.

**Comment by aekiss** [comment]
ok great, I'll try it out

**Comment by russfiedler** [comment]
@nicjhan  Are you sure that this resolves all the issues? I can still see that it is possible to add an increment of a month to a date late in one month and end up with an illegal date e.g. 31 November. Is this definitely caught in the datetime module and the program brought down gracefully?

I'd suggest just straight out killing the model with prejudice if any attempt is made to increment by a month/year and the current day of the month is >28. Actually I'd prefer if it was killed if the day was >1 as the user is almost certainly making a mistake.

**Comment by nicjhan** [comment]
Thanks @russfiedler, I'll add that check before closing the issue.

**Comment by aekiss** [comment]
we need to permit day>1 otherwise there's no way of running for anything between 1 day and 1 month

**Comment by aekiss** [comment]
btw @nic are you building with the latest hashexe.sh ? your exes don't include the libaccessom2 hash

**Comment by russfiedler** [comment]
@aekiss  No, I'm saying that if you want to specify a run using the unit of month then it only makes sense if you start on a day that allows a valid date one month into the future. If you want to specify a number of days thats fine and is handled by `self%restart_period(3) > 0`. It's the case `self%restart_period(2)>0` that can cause problems.

**Comment by aidanheerdegen** [comment]
I think I'd agree with your previous statement @russfiedler that it shouldn't accept any start date with `day > 28` which uses a monthly increment as it is inherently undefined for some months.

**Comment by nic** [comment]
@aekiss Actually a didn't use yet. But it sounds pretty promising. :)
